name: Test SSH
on: [workflow_dispatch]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "✅ Connexion réussie à $(hostname)"
